server:
  port: 8080
  servlet:
    context-path: /forum-overflow
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum
    username: forum
    password: '#forum-2020'
  #    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        lob:
          non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
